Repository DeveloperAcademy-POSTECH/MC3-Team6-HaKenLuRooCo, pull requests merged in 2022-08, with the labels that each got.

#106 #91 feat: CallCheckView 를 Modal로 불러오도록 변경
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu.xcodeproj/xcshareddata/xcschemes/TodayAnbu.xcscheme
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Boards/CallCheck.storyboard
  TodayAnbu/Sources/Controllers/CallCheckViewController.swift
  TodayAnbu/Sources/Controllers/MainViewController.swift
Labels: feature, 코지

#109 #108 feat: onboarding 체크 로직 생성
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Controllers/OnboardingPageViewController.swift
  TodayAnbu/Sources/Models/Storage.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: feature, 코지

#114 #113 fix: 아빠 번호 입력되도록 수정
  TodayAnbu/Sources/Controllers/DadInitViewController.swift
  TodayAnbu/Sources/Controllers/MomInitViewController.swift
Labels: 코지, fix

#112 [Fix]: AboutUsView 버그 수정 완료
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Info.plist
  TodayAnbu/Sources/Boards/AboutUsView.storyboard
  TodayAnbu/Sources/Controllers/AboutUsViewController.swift
  TodayAnbu/Sources/Controllers/AboutUsWebViewController.swift
Labels: bug, 루미, fix

#118 #116 fix: MainView Top Rounded Rectangle 채우기
  TodayAnbu/Sources/Controllers/MainViewController.swift
Labels: 코지, fix

#117 [feat] 세팅 뷰 버튼 및 전화했을시에만 confirmview뜨게 함
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Controllers/TabBarController.swift
  TodayAnbu/Sources/Models/CallModelData.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: feature, 하디

#121 탭바에 메모장 뷰 추가 및 전화했을 시만 전화확인 창 뜨게 함
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Controllers/CallCheckViewController.swift
  TodayAnbu/Sources/Controllers/ConfirmViewController.swift
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Controllers/TabBarController.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: feature, 하디

#123 Feature/119/textfield custom
  Podfile
  Podfile.lock
  Pods/AnyFormatKit/LICENSE
  Pods/AnyFormatKit/README.md
  Pods/AnyFormatKit/Source/Controllers/TextFieldControllers/TextFieldInputController.swift
  Pods/AnyFormatKit/Source/Controllers/TextFieldControllers/TextFieldStartInputController.swift
  Pods/AnyFormatKit/Source/Controllers/TextViewControllers/TextViewInputController.swift
  Pods/AnyFormatKit/Source/Controllers/TextViewControllers/TextViewStartInputController.swift
  Pods/AnyFormatKit/Source/Extensions/String+Extension.swift
  Pods/AnyFormatKit/Source/Extensions/UITextField+Extension.swift
  Pods/AnyFormatKit/Source/Extensions/UITextView+Extension.swift
  Pods/AnyFormatKit/Source/TextFormatter/DefaultFormatters/Formatters/DefaultTextFormatter.swift
  Pods/AnyFormatKit/Source/TextFormatter/DefaultFormatters/Formatters/DefaultTextInputFormatter.swift
  Pods/AnyFormatKit/Source/TextFormatter/DefaultFormatters/Helpers/DefaultCaretPositionCorrector.swift
  Pods/AnyFormatKit/Source/TextFormatter/DefaultFormatters/Helpers/DefaultRangeCalculator.swift
  Pods/AnyFormatKit/Source/TextFormatter/PlaceholderFormatters/Formatters/PlaceholderTextFormatter.swift
  Pods/AnyFormatKit/Source/TextFormatter/PlaceholderFormatters/Formatters/PlaceholderTextInputFormatter.swift
  Pods/AnyFormatKit/Source/TextFormatter/PlaceholderFormatters/Helpers/PlaceholderCaretPositionCalculator.swift
  Pods/AnyFormatKit/Source/TextFormatter/PlaceholderFormatters/Helpers/PlaceholderRangeCalculator.swift
  Pods/AnyFormatKit/Source/TextFormatter/SumFormatters/Formatters/SumTextFormatter.swift
  Pods/AnyFormatKit/Source/TextFormatter/SumFormatters/Formatters/SumTextInputFormatter.swift
  Pods/AnyFormatKit/Source/TextFormatter/SumFormatters/Helpers/SumFormatParser.swift
  Pods/AnyFormatKit/Source/TextFormatter/SumFormatters/Helpers/SumTextInputFormatterCaretPositionCalculator.swift
  Pods/AnyFormatKit/Source/TextFormatter/TextFormatter/CaretPositioner.swift
  Pods/AnyFormatKit/Source/TextFormatter/TextFormatter/FormattedTextValue.swift
  Pods/AnyFormatKit/Source/TextFormatter/TextFormatter/TextFormatter.swift
  Pods/AnyFormatKit/Source/TextFormatter/TextFormatter/TextInputFormatter.swift
  Pods/AnyFormatKit/Source/TextFormatter/TextFormatter/TextNumberFormatter.swift
  Pods/AnyFormatKit/Source/TextFormatter/TextFormatter/TextNumberUnformatter.swift
  Pods/AnyFormatKit/Source/TextFormatter/TextFormatter/TextUnformatter.swift
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Target Support Files/AnyFormatKit/AnyFormatKit-Info.plist
  Pods/Target Support Files/AnyFormatKit/AnyFormatKit-dummy.m
  Pods/Target Support Files/AnyFormatKit/AnyFormatKit-prefix.pch
  Pods/Target Support Files/AnyFormatKit/AnyFormatKit-umbrella.h
  Pods/Target Support Files/AnyFormatKit/AnyFormatKit.debug.xcconfig
  Pods/Target Support Files/AnyFormatKit/AnyFormatKit.modulemap
  Pods/Target Support Files/AnyFormatKit/AnyFormatKit.release.xcconfig
  Pods/Target Support Files/Pods-TodayAnbu/Pods-TodayAnbu-Info.plist
  Pods/Target Support Files/Pods-TodayAnbu/Pods-TodayAnbu-acknowledgements.markdown
  Pods/Target Support Files/Pods-TodayAnbu/Pods-TodayAnbu-acknowledgements.plist
  Pods/Target Support Files/Pods-TodayAnbu/Pods-TodayAnbu-dummy.m
  Pods/Target Support Files/Pods-TodayAnbu/Pods-TodayAnbu-frameworks-Debug-input-files.xcfilelist
  Pods/Target Support Files/Pods-TodayAnbu/Pods-TodayAnbu-frameworks-Debug-output-files.xcfilelist
  Pods/Target Support Files/Pods-TodayAnbu/Pods-TodayAnbu-frameworks-Release-input-files.xcfilelist
  Pods/Target Support Files/Pods-TodayAnbu/Pods-TodayAnbu-frameworks-Release-output-files.xcfilelist
  Pods/Target Support Files/Pods-TodayAnbu/Pods-TodayAnbu-frameworks.sh
  Pods/Target Support Files/Pods-TodayAnbu/Pods-TodayAnbu-umbrella.h
  Pods/Target Support Files/Pods-TodayAnbu/Pods-TodayAnbu.debug.xcconfig
  Pods/Target Support Files/Pods-TodayAnbu/Pods-TodayAnbu.modulemap
  Pods/Target Support Files/Pods-TodayAnbu/Pods-TodayAnbu.release.xcconfig
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu.xcworkspace/contents.xcworkspacedata
  TodayAnbu.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  TodayAnbu/Sources/Controllers/DadInitViewController.swift
  TodayAnbu/Sources/Controllers/MomInitViewController.swift
  TodayAnbu/Sources/Extensions/UITextfieldExtension.swift
Labels: feature, 루미, fix

#127 [fix] ConfirmView 삭제 및 메인화면 레이아웃 수정
  Pods/Pods.xcodeproj/project.pbxproj
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Controllers/ConfirmViewController.swift
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Controllers/OnboardingMainViewController.swift
Labels: 하디, fix

#130 [fix] settingButton 오류 해결함
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Controllers/TabBarController.swift
Labels: 하디, fix

#137 Fix/131 setting modal to navigation
  TodayAnbu/Sources/Controllers/DadInitViewController.swift
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Controllers/MomInitViewController.swift
  TodayAnbu/Sources/Controllers/SettingViewController.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: 코지, fix

#141 Fix/131 setting modal to navigation
  TodayAnbu/Sources/Controllers/DadInitViewController.swift
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Controllers/MomInitViewController.swift
  TodayAnbu/Sources/Controllers/SettingViewController.swift
  TodayAnbu/Sources/Controllers/TabBarController.swift
Labels: 코지, fix

#142 [Refactor]: [#128] Main Button layout 통일
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Controllers/CallCheckViewController.swift
  TodayAnbu/Sources/Controllers/DadInitViewController.swift
  TodayAnbu/Sources/Controllers/MomInitViewController.swift
Labels: 루미, fix

#143 [feat] 전화 카운트 시스템 온
  TodayAnbu/Sources/Controllers/CallCheckViewController.swift
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Extensions/DateFormatting.swift
  TodayAnbu/Sources/Models/CallModelData.swift
Labels: feature, 코지, 하디

#158 Fix/157 design detail revision
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Boards/MemoStoryboard.storyboard
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Controllers/MemoDetailViewController.swift
  TodayAnbu/Sources/Controllers/MemoViewController.swift
  TodayAnbu/Sources/Controllers/SettingViewController.swift
  TodayAnbu/Sources/Controllers/TabBarController.swift
  TodayAnbu/Sources/Models/MemoData.swift
Labels: feature, 루키

#162 Feautre/159 memo to detail
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Resources/Assets.xcassets/OnboardingPic/App_OnboardingFirst.imageset/App_Onboarding_1st.png
  TodayAnbu/Resources/Assets.xcassets/OnboardingPic/App_OnboardingFirst.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/OnboardingPic/App_OnboardingThird.imageset/App_OnboardingThird.png
  TodayAnbu/Resources/Assets.xcassets/OnboardingPic/App_OnboardingThird.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/OnboardingPic/LaunchScreenMiddle.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/OnboardingPic/LaunchScreenMiddle.imageset/LaunchScreenMiddle.png
  TodayAnbu/Sources/Boards/AboutUsView.storyboard
  TodayAnbu/Sources/Boards/Base.lproj/LaunchScreen.storyboard
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Boards/MemoStoryboard.storyboard
  TodayAnbu/Sources/Controllers/CallCheckViewController.swift
  TodayAnbu/Sources/Controllers/MemoDetailViewController.swift
  TodayAnbu/Sources/Controllers/MemoViewController.swift
  TodayAnbu/Sources/Controllers/TabBarController.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: feature, 루키, 켄

#161 Feat/160 widget data binding
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Controllers/CallCheckViewController.swift
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Models/CallModelData.swift
  TodayAnbu/Sources/Models/TopicData.swift
  TodayAnbuWidget/TodayAnbuWidget.swift
Labels: feature, 루키
