Repository DeveloperAcademy-POSTECH/MC3-Team6-HaKenLuRooCo, pull requests merged in 2022-07, with the labels that each got.

#5 #2 feat: OnboardingPage 구현 및 Notification관련 파일 생성
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Resources/Assets.xcassets/FamilyPicture.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/FamilyPicture.imageset/FamilyPicture.png
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Boards/OnboardingPage.storyboard
  TodayAnbu/Sources/Controllers/NotificationSettingViewController.swift
  TodayAnbu/Sources/Controllers/OnboardingPageViewController.swift
Labels: feature, 루키

#11 #3 feat: segmented control & refresh done
  TodayAnbu/Sources/Controllers/MainViewTopicController.swift
Labels: 코지, 하디

#8 [feat] : 3- 메인 토픽 뷰 임시커밋
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Boards/Base.lproj/LaunchScreen.storyboard
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Controllers/MainViewTopicController.swift
  TodayAnbu/Sources/Controllers/ViewController.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: feature, 하디

#10 Feature/1 setting view
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Controllers/SettingViewController.swift
  TodayAnbu/Sources/Models/SettingHeaderView.swift
  TodayAnbu/Sources/Models/SettingPersonalDataCell.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: feature, 켄

#13 feat:NavigationBar 기능과 UI 개발 완료
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Controllers/OnboardingPageViewController.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: feature, 켄

#14 #12 fix : 오토 레이아웃은 zoom모드 문제였음 레이아웃 수정함
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Controllers/MainViewTopicController.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: 하디, fix

#15 feat / 메인뷰 임시 합치는 작업
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: feature, 코지, 켄, 하디

#18 #7 [Feat]: connect UserDefaults & Code Refactor
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Boards/UserInitSettingView.storyboard
  TodayAnbu/Sources/Controllers/UserInitViewController.swift
  TodayAnbu/Sources/Extensions/UITextfieldExtension.swift
Labels: feature, 루미, fix

#21 #20 : MainView Refactor
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: 하디, fix

#23 #22 feat: add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: feature

#26 #24 feat: add auto assign
  .github/auto_assign.yml
Labels: feature

#30 Feature/16 stamp UI
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: feature, 켄

#34 [refactor] : 코드정리
  TodayAnbu/Sources/Controllers/MainViewController.swift
Labels: 하디, fix

#47 #40 attach UIImage TapGesture
  TodayAnbu/Sources/Controllers/MainViewController.swift
Labels: feature, 코지

#50 #49 fix: 스토리보드 warning 해결
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Boards/OnboardingPage.storyboard
  TodayAnbu/Sources/Boards/UserInitSettingView.storyboard
Labels: 루키, fix

#56 #55 fix: deactive tableview scroll
  TodayAnbu/Sources/Controllers/MainViewController.swift
Labels: 코지, fix

#60 #57 fix: develop 브렌치와 다른 것만 Lint 적용 -> 모든 파일에 대하여
  .github/workflows/build-test.yml
Labels: 코지, fix

#65 #64 feature: Custom Color 도입
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Resources/Assets.xcassets/Colors/Contents.json
  TodayAnbu/Resources/Assets.xcassets/Colors/mainIndigo.colorset/Contents.json
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Extensions/UIColor+Extension.swift
  TodayAnbu/Sources/Extensions/UITextfieldExtension.swift
Labels: feature

#67 Feature/63: MainDesign
  .swiftlint.yml
  TodayAnbu/Resources/Assets.xcassets/Colors/dadDeepSkyblue.colorset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/Colors/dadGaugeDeep.colorset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/Colors/dadGaugeLight.colorset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/Colors/dadLightSkyblue.colorset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/Colors/mainTitleFontColor.colorset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/Colors/mainTitleOrange.colorset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/Colors/momDeepPink.colorset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/Colors/momGaugeDeep.colorset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/Colors/momGaugeLight.colorset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/Colors/momLightPink.colorset/Contents.json
  TodayAnbu/Sources/AppDelegate.swift
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Extensions/UIColor+Extension.swift
Labels: feature

#69 #68 feat: 2차 스프린트 LaunchScreen
  TodayAnbu/Resources/Assets.xcassets/ParentPicture.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/ParentPicture.imageset/OnboardingImage.png
  TodayAnbu/Sources/Boards/Base.lproj/LaunchScreen.storyboard
Labels: feature, 코지

#71 Feature/66 refact main view controller (디자인 변경에 따른 메인 뷰 수정)
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: feature, 하디

#75 Feature/63: topArea UI 디자인 완성
  .swiftlint.yml
  TodayAnbu/Resources/Assets.xcassets/ParentPic.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/ParentPic.imageset/ParentPic.png
  TodayAnbu/Sources/Boards/Base.lproj/LaunchScreen.storyboard
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Controllers/TabBarController.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: feature

#77 Feature/73/first onboarding
  TodayAnbu/Resources/Assets.xcassets/dadPicture.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/dadPicture.imageset/dadImage.png
  TodayAnbu/Resources/Assets.xcassets/momPicture.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/momPicture.imageset/momPicture.png
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
Labels: feature, 루미

#76 Feature/7 notification setting seven buttons
  .swiftlint.yml
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Controllers/NotificationModalViewController.swift
  TodayAnbu/Sources/Controllers/NotificationSettingViewController.swift
  TodayAnbu/Sources/Controllers/UserInitViewController.swift
  TodayAnbu/Sources/Extensions/DateFormatting.swift
  TodayAnbu/Sources/Models/NotificationTime.swift
Labels: feature, 루키

#80 Feature/[#73] onboarding controller
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Controllers/OnboardingMainViewController.swift
Labels: feature, 루미

#83 Feature/74 세팅 뷰 구현 및 백 투 포그라운드 작업
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Controllers/ConfirmViewController.swift
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Controllers/SettingViewController.swift
Labels: feature, 하디

#87 Feature/78 memo UI
  .swiftlint.yml
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Boards/MemoStoryboard.storyboard
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Controllers/MemoViewController.swift
  TodayAnbu/Sources/Models/MemoCell.swift
  TodayAnbu/Sources/Models/MemoData.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: feature

#85 Feature/[ #82 ] Complete seven button UI & Add DadInitController
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Controllers/DadInitViewController.swift
  TodayAnbu/Sources/Controllers/MomInitViewController.swift
Labels: feature, 루키, 루미, fix

#90 Feat/70 89 call check view
  .swiftlint.yml
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Sources/Boards/CallCheck.storyboard
  TodayAnbu/Sources/Controllers/CallCheckViewController.swift
  TodayAnbu/Sources/Extensions/DateFormatting.swift
Labels: feature, 코지

#93 Feature/84 back tofore call value
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu.xcodeproj/xcshareddata/xcschemes/TodayAnbu.xcscheme
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Controllers/ConfirmViewController.swift
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Models/CallModelData.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: feature, 루키, 하디

#94 Feat/91 enhance tapgesture
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Boards/CallCheck.storyboard
  TodayAnbu/Sources/Controllers/CallCheckViewController.swift
Labels: feature, 코지

#95 Feature: [ #86 ] AboutUsView UI & 기능 구현(추후 수정)
  TodayAnbu.xcodeproj/project.pbxproj
  TodayAnbu/Info.plist
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/Contents.json
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/HakenLuRooCo.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/HakenLuRooCo.imageset/HakenLuRooCo.png
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/githubFrames/Contents.json
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/githubFrames/cozyFrame.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/githubFrames/cozyFrame.imageset/cozyFrame.png
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/githubFrames/hardyFrame.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/githubFrames/hardyFrame.imageset/hardyFrame.png
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/githubFrames/kenFrame.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/githubFrames/kenFrame.imageset/kenFrame.png
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/githubFrames/lumiFrame.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/githubFrames/lumiFrame.imageset/lumiFrame.png
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/githubFrames/rookieFrame.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/githubFrames/rookieFrame.imageset/rookieFrame.png
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/githubPicture.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/AboutUsPic/githubPicture.imageset/githubPicture.png
  TodayAnbu/Resources/Assets.xcassets/HakenLuRooCoPic/Contents.json
  TodayAnbu/Resources/Assets.xcassets/HakenLuRooCoPic/Cozy.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/HakenLuRooCoPic/Cozy.imageset/Cozy.png
  TodayAnbu/Resources/Assets.xcassets/HakenLuRooCoPic/Hardy.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/HakenLuRooCoPic/Hardy.imageset/Hardy.png
  TodayAnbu/Resources/Assets.xcassets/HakenLuRooCoPic/Ken.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/HakenLuRooCoPic/Ken.imageset/Ken.jpeg
  TodayAnbu/Resources/Assets.xcassets/HakenLuRooCoPic/Lumi.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/HakenLuRooCoPic/Lumi.imageset/Lumi.jpg
  TodayAnbu/Resources/Assets.xcassets/HakenLuRooCoPic/Rookie.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/HakenLuRooCoPic/Rookie.imageset/Rookie.png
  TodayAnbu/Resources/Assets.xcassets/OnboardingPic/Contents.json
  TodayAnbu/Resources/Assets.xcassets/OnboardingPic/FamilyPicture.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/OnboardingPic/FamilyPicture.imageset/FamilyPicture.png
  TodayAnbu/Resources/Assets.xcassets/OnboardingPic/ParentPic.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/OnboardingPic/ParentPic.imageset/ParentPic.png
  TodayAnbu/Resources/Assets.xcassets/OnboardingPic/dadPicture.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/OnboardingPic/dadPicture.imageset/dadImage.png
  TodayAnbu/Resources/Assets.xcassets/OnboardingPic/momPicture.imageset/Contents.json
  TodayAnbu/Resources/Assets.xcassets/OnboardingPic/momPicture.imageset/momPicture.png
  TodayAnbu/Sources/Boards/AboutUsView.storyboard
  TodayAnbu/Sources/Controllers/AboutUsViewController.swift
  TodayAnbu/Sources/Controllers/AboutUsWebViewController.swift
Labels: feature, 루미

#100 #99 feat: 세로모드 & 라이트모드 고정
  TodayAnbu/Info.plist
  TodayAnbu/Sources/AppDelegate.swift
Labels: feature

#105 Fix/onboarding layout [ #103 ]
  TodayAnbu/Sources/Boards/Base.lproj/Main.storyboard
  TodayAnbu/Sources/Controllers/ConfirmViewController.swift
  TodayAnbu/Sources/Controllers/MainViewController.swift
  TodayAnbu/Sources/Models/CallModelData.swift
  TodayAnbu/Sources/SceneDelegate.swift
Labels: 루미, fix
